### PR TITLE
Backend tool option

### PR DESCRIPTION
**Pull request by StudioEtrange**
Add option to choose a backend tool.

In some case, we dont have scanelf binary, but readelf

So we can choose to change the default one (scanelf)

### CODE REVIEW

**Comment by StudioEtrange** [comment]
example :

# Use scanelf

./lddtree.sh $(which ps)
./lddtree.sh -b scanelf $(which ps)

# Use readelf

./lddtree.sh -b readelf $(which ps)

**Comment by ncopa** [comment]
I am not against this, but I'd like to move every `if [ "$BACKEND" = "scanelf" ]; then ... elif [ "$BACKED" = "readelf" ]; then ... fi`into  wrapper functions. For example:

``` sh

# readelf variants
do_something_readelf() {
    readelf --something $1 ....
}

foobar_readelf() {
   readelf --foobar $@ ....
}

# scanelf variants
do_something_scanelf() {
    scanelf --some-thing $1 ....
}

foobar_scanelf() {
    scanelf --foo-bar $@ ....
}

BACKEND=scanelf

# abstraction wrapper functions
do_something() {
    do_something_$BACKEND "$@"
}

foobar() {
   foobar_$BACKEND "$@"
}

```

And then we replace:

``` sh
if [ "$BACKEND" = "scanelf" ]; then
    scanelf --some-thing ....
elif [ "$BACKEND" = "readelf" ]; then
    readelf --something ....
fi
```

with:

``` sh
do_something ....
```

**Comment by StudioEtrange** [comment]
Ok.

Then, I made wrapper functions.

**And first I posted two fixes :**
- Use of g flag with sed when replace of $ORIGIN in RPATH. Because we may have several $ORIGIN in rpath

> scanelf -qF '#F%r' "${_file}" | sed -e "s:[$]ORIGIN:${_file%/*}:g"
- When we pass a relative elf path, RPATH wich contains $ORIGIN are turned into relative path and might not be resolved

> [ -z "${path##/*}" ] || path="${PWD}/${path}"
> 
> stella>objdump -p tutu/libpng/1_6_17/lib/libpng.so | grep RUNPATH
>   RUNPATH              $ORIGIN/../stella-dep:$ORIGIN/stella-dep
> 
> stella>./nix/pool/artefact/lddtree/lddtree.sh -b scanelf tutu/libpng/1_6_17/lib/libpng.so  
> libpng.so => tutu/libpng/1_6_17/lib/libpng.so (interpreter => none)
>     libz.so.1 => /stella/tutu/libpng/1_6_17/lib/../stella-dep/libz.so.1
>     libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6
>         ld-linux-x86-64.so.2 => /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
>     libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6`

**And second I added two more options :**
- --no-header which do not print analysed elf and its interpreter
- --no-recursive to not analyse dependencies of dependencies

**And Last, I have a question**
- AUTO ROOT option seems to replace the root of elf path only if we use absolute path. Is it right ?

> if ${AUTO_ROOT} && [ -z "${elf##/*}" ] ; then elf="${ROOT}${elf#/}"; fi

**Comment by ncopa** [comment]
can you please split the commit with wrapper function and new options and rebase?

**Comment by StudioEtrange** [comment]
Ok i will do a complete fresh pull request with 3 split commit...
one for fixes, one for backend, one for no-header/no-recursive

Is this ok for you ?

Or do you want, 3 distincts PR ?

**Comment by ncopa** [comment]
one pr and 3 commits sounds good :+1:

but you dont need create new PR, i think you can `git push --force` and the commits in this PR will be updated.

**Comment by ncopa** [comment]
i pushed the feature in 2 logic steps:
- refactor to use scanelf via wrapper
- add binutils wrapper, and use this if scanelf is not found

Can you please verify that this works for you and the also provide the fixes in separate PR?

Thanks!

**Comment by StudioEtrange** [comment]
Oh man
I have just pushed all my modifications and fixes to my forked version to analyse the whole diffs.

There is a lot. And as I was so in a hurry and not so well organized, my commits groups several different topic. In a word : it's a kind of mess.

There is 4 new options : no recursive, no header, list only  dependencies (-m), force a backend (-b)
Support for multiple rpath values (with /g on sed expressions)
And a few fixes I cant remember

Actually I have integrated my forked version into a bigger tools (https://github.com/StudioEtrange/stella) and I use lddtree with another script I made (https://github.com/StudioEtrange/stella/blob/master/nix/common/lib-parse-bin.sh)
to be able to analyse any kind of binary

But I will try my best, when I will have time, to push options and fixes upstream to your repo.

**Comment by ncopa** [comment]
> @StudioEtrange  And as I was so in a hurry and not so well organized, my commits groups several different topic. In a word : it's a kind of mess.

This is main reason I didn't merge it.

**Comment by StudioEtrange** [comment]
I know...
Ok, everything done.
For now, I have posted 2 PR.
And I will have 2 more waiting in separate branches that i will create after you merge PR#1 and PR#2. If you wish.

Every PR have a limit number of commits and is dedicated to a specific topic

**Pull request closed without merging**
